### ISSUE TITLE
cpl info is too ambigous? maybe `cpl diff`

### ISSUE THREAD

**Issue by justin808** [shakacode/heroku-to-control-plane#154]
What would I like cpl info to give me:

* Link to controlplane.yml file (on Github?)
* List of apps and orgs
* Links to console and deployed apps
* Tips

Some ideas for what it could contain:

```
hichee-production: #  org
  - hichee-production: # app https://console.cpln.io/console/org/hichee-production/gvc/hichee-production/workload
    - workloads-deployed # names matching 
      - rails:
      - criticalworker
      - worker
      - syncworker
      - matchworker
    - missing-from-config: # manually added
      - hardworker
      - image-scaler
      - maintenance
      - memcached
      - memcached-rack-attack

hichee-staging: # org https://console.cpln.io/console/org/hichee-staging/gvc/hichee-staging/workload
  - hichee-staging
    - workloads-deployed # names matching 
      - rails
      - sidekiq
      - redis
      - memcached
    - missing-from-config: # manually added 
      - images-scaler
      - maintenance
  - hichee-storybook # app https://console.cpln.io/console/org/hichee-staging/gvc/hichee-storybook/workload
    - workloads-deployed # names matching
      - storybook
      - rails
  - hichee-review-7393
    - rails
    - sidekiq
    - redis
    - memcached
  - hichee-review-7403
    - rails
    - sidekiq
    - redis
    - memcached
  - hichee-review-7424
    - rails
    - sidekiq
    - redis
    - memcached


Some apps/workloads are missing. Please create them with:
  - `cpl apply-template rails -a hichee-storybook`

There are no apps starting with some names. If you wish to create any, do so with (replace 'whatever' with whatever suffix you want):
  - `cpl setup-app -a hichee-storybook-review-whatever
```
