### ISSUE TITLE
cpl setup ==> cpl apply-template and cpl setup-app

### ISSUE THREAD

**Issue by justin808** [shakacode/heroku-to-control-plane#28]
Good point. Let's do this:

# `cpl apply-template`
1. rename `cpl setup` to `cpl apply-template`
1. Check object exists for app. If so, then require an additional option: `--confirm <app_name>` . If we can't check if the object exists, the always require `--confirm <app_name>`

![2023-04-26_08-46-47](https://user-images.githubusercontent.com/1118459/234673969-03eba2d7-3309-473d-ab2a-1b6f94be1677.png)

# `cpl setup-app`
1. Add array of templates to optional key `setup` under the app in `controlplane.yml`

example:
```yml
apps:
  hichee-staging:
    <<: *common
  hichee-review-:
    <<: *common
    match_if_app_name_starts_with: true
    stale_app_image_deployed_days: 5
    # setup should only be used for review apps, never for persistent apps like production
    setup:
      - gvc
      - identity
      - redis
      - memcached
      - rails
      - sidekiq
```

3. Add a command that will apply 

`cpl setup-app -a <app_name>`

If app exists, return error code 1 and display message:

Error! App <app_name> already exists. If you want to update this app, either run `cpl delete -a <APP_NAME>` and rerun, or run `cpl apply-template <template1> <template2> -a <APP_NAME>`.

![2023-04-26_08-45-46](https://user-images.githubusercontent.com/1118459/234673996-8e0e66b0-c2ef-4e38-a9ba-68515660b029.png)

**Comment by rafaelgomesxyz** [comment]
Not sure I understand. As far as I can tell, `cpl setup` doesn't delete anything?

> * `cpl setup` should fail if:
>  1. If any of the templates are missing (first check list of templates)  
>  1. If **not** using `allow_setup: true` for the app

I've done the first one so far: https://github.com/shakacode/heroku-to-control-plane/pull/33

But regarding the second one, if the goal is to prevent workloads from being recreated, wouldn't a better solution be to check if the workload already exists and fail if that's the case? Having to configure `allow_setup: true` to be able to use `cpl setup` feels like a nuisance.

**Comment by justin808** [comment]
Good point. Let's do this:

# `cpl apply-template`
1. rename `cpl setup` to `cpl apply-template`
1. Check object exists for app. If so, then require an additional option: `--confirm <app_name>` . If we can't check if the object exists, the always require `--confirm <app_name>`

![2023-04-26_08-45-46](https://user-images.githubusercontent.com/1118459/234673996-8e0e66b0-c2ef-4e38-a9ba-68515660b029.png)


# `cpl setup-app`
1. Add array of templates to optional key `setup` under the app in `controlplane.yml`

example:
```yml
apps:
  hichee-staging:
    <<: *common
  hichee-review-:
    <<: *common
    match_if_app_name_starts_with: true
    stale_app_image_deployed_days: 5
    # setup should only be used for review apps, never for persistent apps like production
    setup:
      - gvc
      - identity
      - redis
      - memcached
      - rails
      - sidekiq
```

3. Add a command that will apply 

`cpl setup-app -a <app_name>`

If app exists, return error code 1 and display message:

Error! App <app_name> already exists. If you want to update this app, either run `cpl delete -a <APP_NAME>` and rerun, or run `cpl apply-template <template1> <template2> -a <APP_NAME>`.



![2023-04-26_08-46-47](https://user-images.githubusercontent.com/1118459/234673969-03eba2d7-3309-473d-ab2a-1b6f94be1677.png)
