### ISSUE TITLE
Updates to CLI Ideas

### ISSUE THREAD

**Issue by justin808** [shakacode/heroku-to-control-plane#8]
# Pending Name Changes
- [ ] `promote-image` ==> `deploy-image`

# Missing Commands
- [ ] `promote-app-from-upstream -a hichee-production` ==> uses the `upstream` yaml app name. Includes steps like the below CI example

# Example of promote-app-from-upstream done via CircleCI steps

```yaml
  controlplane-release-production:
    docker:
      # this node version is for for controlplane cli, it may be different from hichee node version
      - image: cimg/ruby:3.1-node
    # resource_class: large
    environment:
      CPLN_ORG_STAGING: hichee-staging
      APP_NAME_STAGING: hichee-staging
      CPLN_ORG_PRODUCTION: hichee-production
      APP_NAME_PRODUCTION: hichee-production
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Control Plane tools
          command: |
            sudo npm install -g @controlplane/cli && cpln --version

            gem install cpl
      - run:
          name: Copy image
          command: |
            cpln profile create default --token ${CPLN_TOKEN} --org ${CPLN_ORG_STAGING} --gvc ${APP_NAME_STAGING}

            IMAGE_NAME_STAGING=$(cpl latest-image -a hichee-staging)
            IMAGE_NAME_PRODUCTION=$(echo $IMAGE_NAME_STAGING | sed "s/[^:]*/${APP_NAME_PRODUCTION}/")

            IMAGE_URL_STAGING=${CPLN_ORG_STAGING}.registry.cpln.io/${IMAGE_NAME_STAGING}
            IMAGE_URL_PRODUCTION=${CPLN_ORG_PRODUCTION}.registry.cpln.io/${IMAGE_NAME_PRODUCTION}

            echo $IMAGE_URL_STAGING
            echo $IMAGE_URL_PRODUCTION

            cpln image docker-login
            docker pull ${IMAGE_URL_STAGING}

            CPLN_TOKEN=$CPLN_TOKEN_PRODUCTION
            cpln profile update default --token ${CPLN_TOKEN} --org ${CPLN_ORG_PRODUCTION} --gvc ${APP_NAME_PRODUCTION}
            cpln image docker-login

            docker tag ${IMAGE_URL_STAGING} ${IMAGE_URL_PRODUCTION}

            docker push ${IMAGE_URL_PRODUCTION}
      - run:
          name: Release phase including database tasks
          command: |
            CPLN_TOKEN=$CPLN_TOKEN_PRODUCTION
            cpl run:detached 'LOG_LEVEL=warn rails db:migrate' -a ${APP_NAME_PRODUCTION} --image latest
      - run:
          name: Deploy latest image
          command: |
            CPLN_TOKEN=$CPLN_TOKEN_PRODUCTION
            cpl deploy-image -a ${APP_NAME_PRODUCTION}
```
