### ISSUE TITLE
Rename `controlplane.yml` key `setup` to `setup_app_workloads` for clarity

### ISSUE THREAD

**Issue by ahangarha** [shakacode/heroku-to-control-plane#96]
From #91 
---

**Comment by ahangarha** [comment]
Currently we have such configurations:
```yaml
my-app-staging:
  <<: *common
  setup:
    - gvc
    - redis
    - memcached
    - rails
    - sidekiq
```

The `setup` entry includes more than only app_workloads!
Is this intended? If yes, what about other workloads?
